### ISSUE TITLE
Sorting of Parameters

### ISSUE THREAD

**Issue by 28Smiles** [javalin/javalin-openapi#119]
Why are parameters sorted by name?
https://github.com/javalin/javalin-openapi/blob/main/openapi-annotation-processor/src/main/kotlin/io/javalin/openapi/processor/OpenApiGenerator.kt#L143

Doing it this way with every new parameter introduced, the api will break for no aparrent reason. For example i have an endpoint with the following signature:
```
something(id: string, limit?: number, offset?: number)
```
And I am adding a queryParameter `authorId?: number`, then my api will completely change, even if i explicitly put it in the end of the query parameters:
```
something(id: string, authorId?: number, limit?: number, offset?: number)
```
Why isn't the ordering perserved like in the old plugin?

Also if i am creating services from the api, this will result in a silent break, since both parameters are of the same type. This is even more concering for me.

**Comment by dzikoysk** [comment]
This change was introduced in:

* https://github.com/javalin/javalin-openapi/issues/86

Btw it sounds quite strange that query parameters matching is based on top of its order. It should be matched by property names, right?

**Comment by dzikoysk** [comment]
I see the point behind this and I don't have strong opinion on that as OpenApi specification doesn't really cover that scenario, so it's pretty much up to the implementation. Tools you use to generate bindings assume you'll keep order, so it's more like an enhancement request to simplify integration with 3rd party generators rather than a bug. I think we can keep try to keep the declaration order, would you like to submit PR or should I do it?

**Comment by 28Smiles** [comment]
ill submit it
