### ISSUE TITLE
Internationalisation (I18N) support

### ISSUE THREAD

**Issue by p4paul** [javalin/javalin-openapi#155]
Is it possible to provide Internationalisation support for OpenAPI annotations, ideally using Java properties files.

Spring has the `@PropertySource("classpath:config.properties")` option and then uses `@Value("${org.domain.some.key}")`.

Perhaps the Javalin plugin could do something something like:
```
  @OpenApi(
    path = "/login",
    propertySource = "classpath:config.properties",
    summary = "${org.domain.login.summary}",
    requestBody = @OpenApiRequestBody(
      description = "${org.domain.login.description}",
      content = {@OpenApiContent(from = LoginRequestModel.class)}
    ),
    ...
```

**Comment by p4paul** [comment]
Properties files could all be loaded at compile time; but language support at runtime would be nice.  
```
Messages.properties
Messages_en_GB.properties
Messages_zh_CN.properties
...
```
We could uses a System property at runtime to determine the language and set the Locale.
`Locale.setDefault(new Locale("en", "GB"));`
or at launch
`java -jar anApp.jar -Duser.language=en-GB`

**Comment by dzikoysk** [comment]
I think you can already do that with custom annotation processor. You could use such placeholders in annotations and then replace those values in final docs file:

https://github.com/javalin/javalin-openapi/blob/781ee46d3268595bbbc98ed17b942a8055f8f0f8/examples/javalin-gradle-kotlin/src/main/java/io/javalin/openapi/plugin/test/JavalinTest.java#L121-L124

It'd be better if you'd implement this in your app, mostly because you can define multiple sources of those translations etc. and integrate it with your docs.
