### ISSUE TITLE
What is openapi.groovy?

### ISSUE THREAD

**Issue by jflebeau** [javalin/javalin-openapi#179]
Getting this log on stderr: "Note: /_project-path_/src/main/compile/openapi.groovy", I didn't see any mention of it in the docs, just curious to know what it is.

**Comment by dzikoysk** [comment]
This is a special script file introduced in 5.3.0 that allows us to customize annotation processing phase:

* https://github.com/javalin/javalin-openapi/releases/tag/5.3.0

Annotation processing API does not really provide helpful tools to access sources during compilation phase, so we're composing this location on top of the processed source files:

https://github.com/javalin/javalin-openapi/blob/e26c056f34d873dec42765d65173745ef5bc0bbe/openapi-annotation-processor/src/main/kotlin/io/javalin/openapi/processor/configuration/OpenApiPrecompileScriptingEngine.kt#L23-L33

Because this implementation is based on some assumptions related to how usually Java project looks like, I decided to log this path explicitly, so users will know where to put such script. Speaking of the available API, here's an example of various supported options:

* https://github.com/javalin/javalin-openapi/blob/main/openapi-annotation-processor/src/test/compile/openapi.groovy

It's kinda complex, but that's the only way to resolve some issues related to integrating 3rd party libraries with our generator.
