### ISSUE TITLE
Programatically Define Documentation

### ISSUE THREAD

**Issue by MrThreepwood** [javalin/javalin-openapi#219]
All our projects were previously programmatically defining our open api docs with javalin. Has support for that been dropped? How do you do that now?

**Comment by dzikoysk** [comment]
Hey, sorry for late response - I missed this question. Technically it was not dropped, because this is just a completely different plugin that replaced the old now and I simply never implemented that. It was already requested tho, and progress can be tracked here: 

* #146 

The problem here is that currently, this plugin works at compile-time, so it basically rewriting the whole docs builder in order to have it supported.
