### ISSUE TITLE
Feature Request: Option to map Instant to number instead of string

### ISSUE THREAD

**Issue by joshuastorch** [javalin/javalin-openapi#57]
The old openapi plugin allowed to map java Instant to number if the mapper was configured accordingly.

**Comment by dzikoysk** [comment]
You should be able to enforce other type with `@OpenApiPropertyType(definedBy = Type.class)` annotation, e.g.

```
@OpenApiPropertyType(definedBy = Long.class)
public Instant getTime() {}
```

Or do you think we should just convert all `Instant` types to number by default?

**Comment by palmenhq** [comment]
For me, I'm using jackson with `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` `true` and `SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS` `false`. This means that in practice, my `Instant` properties will serialize to something like `1703200822767`. But in my api docs, I'm seeing `string <date-time>` (with example `2019-08-24T14:15:22Z`) as the type for my `Instant` properties.

As i understand your response here @dzikoysk it can be solved by using the `definedBy = Long::class` option on every property that uses `Instant` right now? Sounds a bit clunky and error-prone for me. Is there no option to convert `Instant` to `Long` or `Double` by default? Or even better - read the option from jackson (as topic creator suggests).

**Comment by dzikoysk** [comment]
Reading these options from Jackson would be a clunky solution as well, because:

1. Documentation is a bit different topic than serialization rules
2. Having Jackson oriented implementation would be simply wrong for other serialization libraries
3. It'd give a false sense of Jackson support - it's really complex library with hundreds of configuration variants and it'd be basically a source of issues for us. To be fair, that was even the case for old OpenApi plugin that were bundled with Javalin

If you want to provide some customized behavior, you can use a little bit of a dark magic and write a Groovy script that changes all instants to longs. By default, `Instant` is mapped this way:

```
"java.time.Instant" to SimpleType("string", "date-time"),
```

So you can create the `openapi.groovy` file, like that:

* https://github.com/javalin/javalin-openapi/blob/main/examples/javalin-gradle-kotlin/src/main/compile/openapi.groovy

And do something like that:

```java
import io.javalin.openapi.experimental.ExperimentalCompileOpenApiConfiguration
import io.javalin.openapi.experimental.OpenApiAnnotationProcessorConfiguration
import io.javalin.openapi.experimental.OpenApiAnnotationProcessorConfigurer
import io.javalin.openapi.experimental.SimpleType

@ExperimentalCompileOpenApiConfiguration
class OpenApiConfiguration implements OpenApiAnnotationProcessorConfigurer {

    @Override
    void configure(OpenApiAnnotationProcessorConfiguration configuration) {
        configuration.simpleTypeMappings['java.time.Instant'] = new SimpleType("integer", "int64")
    }

}
```

On Gradle it seems to work quite well, especially that Groovy is already loaded by JVM. Not sure about Maven :/
